# Generated by Django 5.2.7 on 2025-11-10 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tucanasta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('supermercado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyme', to='tucanasta.supermercado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pyme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
