# Generated by Django 5.2.7 on 2025-11-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tucanasta', '0002_pyme'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyme',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='pyme_docs/'),
        ),
    ]
